### ISSUE TITLE
docker 컨테이너 최초 실행 시 기업 정보 적재

### ISSUE THREAD

**Issue by namugach** [namugach/neojune#9]
## Description
도커 실행시 엑셀에 있는 2만개의 사업자 등록 번호를 db에 적재하는 로직을 실행

## todo
- [x] load_xlsx_to_db.py를 기점으로 실행 🛫 2024-10-25 
	- [x] create_table.sql 🛫 2024-10-25 
	- [x] data에 있는 데이터를 활용 🛫 2024-10-25 
	- [x] docker 최초 실행시 실행 🛫 2024-10-25 
	- [x] dockerFile 수정🛫 2024-10-25
